### numpy 실습

In [3]:
import numpy as np
np.__version__

'1.23.5'

In [6]:
a = np.array([[1,2,3],[4,5,6]])

In [14]:
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8


In [28]:
a = np.array([2,3,4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

c = np.ndarray((2,2)) # ndarray는 랜덤한 값이 들어감
print(c)

d = np.array([[1,2],[3,4]], dtype = complex) #complex 타입은 복소수 형태
print(d)
print(d.dtype)


[2 3 4]
int64
float64
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [32]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
print(np.ones((2,3,4), dtype=np.int16)) #2*3*4의 3차원 배열

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [43]:
a = np.arange(10, 30, 5)
print(a)

b = np.arange(0, 2, 0.3) # 0부터 2까지 0.3씩 증가 
print(b) 

c = np.linspace(0,2,9) # 일정 간격을 띄우고 출력
print(c)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [141]:
import sys

a = np.arange(10000)
print(a)

b = np.arange(10000).reshape(100, 100) # 100*100 행렬로 생성
print(b)

np.set_printoptions(threshold = sys.maxsize) # threshold는 해당 값을 넘으면 생략함

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [72]:
x = np.arange(100, 110)
print(x)

print(x[-2])

x.resize(2,5) # 2*5 형태로 재배치
print(x)

print(x[1,3]) # 1번째 행, 3번째 열의 원소 출력

print(x[0]) # 0번째 행 전부 다 출력
print(x[0][3]) # 0번째 행에서의 3번째 열 원소 출력

[100 101 102 103 104 105 106 107 108 109]
108
[[100 101 102 103 104]
 [105 106 107 108 109]]
108
[100 101 102 103 104]
103


In [76]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print(a[[0,1,2,0],[0,2,0,1]])
#a[0,0] => 1
#a[1,2] => 6
#a[2,0] => 7
#a[0,1] => 2

b = np.array([0,2,0,1])
print(a[b,b])
#a[0,0] => 1
#a[2,2] => 9
#a[0,0] => 1
#a[1,1] => 5


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 6 7 2]
[1 9 1 5]


In [86]:
x = np.arange(10)
print(x)

print(x[2:5]) # [시작점:도착점:step] [2:5] => 2에서 5까지 (step은 지정안하면 1이됨)

print(x[:-7]) #x[3]

print(x[1:7:2])

y = np.arange(35).reshape(5,7)
print(y)


print(y[1:5:2])
print(y[1:5:2, ::3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2]
[1 3 5]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7  8  9 10 11 12 13]
 [21 22 23 24 25 26 27]]
[[ 7 10 13]
 [21 24 27]]


In [92]:
a = np.array(range(6)).reshape(2,3)
print(a)

bool_idx = a > 2  # a>2 크면 true로 저장, 아니면 false로 저장
print(bool_idx)

print(a[bool_idx]) # true인 값만 가져옴

print(a[a>2]) # 위와 같은 결과 나옴


[[0 1 2]
 [3 4 5]]
[[False False False]
 [ True  True  True]]
[3 4 5]
[3 4 5]


In [103]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

b = a[:2] # 얕은 복사가 일어남
print(b)

c = a[:,1:3] # 모든 행, 그리고 열은 1부터 3 전까지 
print(c)

b[0,0] = -1  # 위에서 얕은 복사때문에, a 값도 변경됨
print(b)
print(a)

b = np.copy(a[:2]) # 깊은 복사


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[-1  2  3  4]
 [ 5  6  7  8]]
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [121]:
a = np.floor( 10* np.random.random((3,4))) # random 함수는 0~1사이의 random 값을 만들기 때문에 곱해서 사용
print(a)

print(a.shape)
print(a.ravel()) # 모든 함수들을 납작하게 1차원 배열로 바꿔서 표현해줌 (a 행렬 자체가 변하지는 않음)
print(a)

print(a.reshape(6,2)) # 6*2형태로 변경 (resize와 비슷한 함수) (a 행렬 자체가 변하지는 않음)
print(a)
a.resize((6,2)) # resize는 아예 a 행렬을 바꿔버림
print(a) 

print(a.T) # 전치 행렬

[[7. 9. 1. 9.]
 [7. 0. 8. 5.]
 [8. 0. 8. 8.]]
(3, 4)
[7. 9. 1. 9. 7. 0. 8. 5. 8. 0. 8. 8.]
[[7. 9. 1. 9.]
 [7. 0. 8. 5.]
 [8. 0. 8. 8.]]
[[7. 9.]
 [1. 9.]
 [7. 0.]
 [8. 5.]
 [8. 0.]
 [8. 8.]]
[[7. 9. 1. 9.]
 [7. 0. 8. 5.]
 [8. 0. 8. 8.]]
[[7. 9.]
 [1. 9.]
 [7. 0.]
 [8. 5.]
 [8. 0.]
 [8. 8.]]
[[7. 1. 7. 8. 8. 8.]
 [9. 9. 0. 5. 0. 8.]]


In [127]:
a = np.floor( 10* np.random.random((3,4))) # random 함수는 0~1사이의 random 값을 만들기 때문에 곱해서 사용
print(a)

print(a.reshape((6,-1)))  # 앞에만 shape의 크기를 정해주고, 뒤에 -1을 넣으면 알아서 맞게 변경해줌


[[6. 3. 0. 3.]
 [0. 2. 8. 3.]
 [7. 4. 0. 6.]]
[[6. 3.]
 [0. 3.]
 [0. 2.]
 [8. 3.]
 [7. 4.]
 [0. 6.]]


In [133]:
a = np.floor(10 * np.random.random((2,2)))
b = np.floor(10 * np.random.random((2,2)))

print(a)
print()
print(b)
print()
print(np.vstack((a,b))) # 수직으로 합치기
print()
print(np.hstack((a,b))) # 수평으로 합치기


[[8. 9.]
 [8. 4.]]

[[4. 3.]
 [4. 2.]]

[[8. 9.]
 [8. 4.]
 [4. 3.]
 [4. 2.]]

[[8. 9. 4. 3.]
 [8. 4. 4. 2.]]


In [137]:
a = np.floor(10 * np.random.random(12)).reshape(2,6)
print(a)

print(np.hsplit(a, 3)) # 수평으로 나눠버림

[[1. 0. 4. 2. 9. 7.]
 [2. 1. 0. 2. 1. 5.]]
[array([[1., 0.],
       [2., 1.]]), array([[4., 2.],
       [0., 2.]]), array([[9., 7.],
       [1., 5.]])]


In [140]:
a = np.floor(10 * np.random.random(12)).reshape(2,6)
print(a)

print(np.vsplit(a, 2)) # 수직으로 나눠버림

[[9. 7. 3. 1. 9. 1.]
 [9. 5. 8. 7. 2. 8.]]
[array([[9., 7., 3., 1., 9., 1.]]), array([[9., 5., 8., 7., 2., 8.]])]


### 실습 문제1

In [153]:
a = np.zeros((5,5))
a[1:4,1:4] = 1

b = np.ones((5,5))
b[1:4,1:4] = 0

print(a)
print()
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [176]:
x = np.zeros((3,3))
print(x)
print()

x = np.pad(x, pad_width = 1, mode = 'constant' , constant_values = 1)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 실습 문제 2


In [161]:
a = np.zeros((8,8))
a[0:7:2, 1::2] = 1
a[1:8:2, ::2] = 1

print(a)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [192]:
a = np.zeros((8,8))
a[1::2, 1::2] = 1
a[::2, ::2] = 1

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 실습 문제 3

In [195]:
a = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
print(a)

a.resize((2,4,2))

print(a)
print(a[0,0,1])

[180  72 172  66 162  60 167  53 176  80 155  60 177  77 130  40]
[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]
72


### Basic Operations (기본 연산자)

In [206]:
x = np.array([[1,2],
               [3,4]])
y = np.array([[5,6],
               [7,8]])

print(x)
print(y)

print(x+y)
print(x-y)
print(x*y)
print(x/y)

print (x@y)  # 행렬곱

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [207]:
a = np.array([20,30,40,50])
print(a)

print(np.sin(a))



[20 30 40 50]
[ 0.91294525 -0.98803162  0.74511316 -0.26237485]


In [212]:
a = np.random.random((2,3))

print(a)
print(a.sum())

[[0.95251714 0.82346358 0.37760022]
 [0.87835624 0.12339683 0.34469358]]
3.500027584421052


In [216]:
b = np.arange(3)
print(b)
print(np.exp(b)) # 지수분포
print(np.sqrt(b)) 
 


[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


### broadcasting

In [222]:
x = np.array((range(1,13))).reshape(4,3)
print(x)
print()

v = np.array([1,0,1])
print(v)
print()

y = x+v

print(y) # 행 개수가 맞지 않지만, brodacasting이 일어나서 연산이 됨

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
